# Nushell entrypoint. Functional configuration lives in modules/.

source ~/.config/nushell/modules/core.nu
source ~/.config/nushell/modules/prompt.nu
source ~/.config/nushell/modules/completions.nu
source ~/.config/nushell/modules/proxy.nu
source ~/.config/nushell/modules/commands.nu

# Generated by `zoxide init nushell`; see README.md.
source ~/.zoxide.nu
