# Lightweight Nushell entrypoint for Zed's integrated terminal.
# Zed starts Nushell with --no-config-file, so vendor autoload scripts such as
# Starship are skipped. Fastfetch is intentionally not invoked here.

$env.config.show_banner = false
$env.config.buffer_editor = "nvim"
$env.EDITOR = "nvim"
$env.VISUAL = "nvim"

let yazi_file = 'C:\Program Files\Git\usr\bin\file.exe'
if ($yazi_file | path exists) {
    $env.YAZI_FILE_ONE = $yazi_file
}

$env.config.shell_integration.osc7 = true
$env.config.rm.always_trash = true
$env.config.table.index_mode = "auto"

source ~/.config/nushell/modules/completions.nu
source ~/.config/nushell/modules/proxy.nu
source ~/.config/nushell/modules/commands.nu

# Generated by `zoxide init nushell`; see README.md.
source ~/.zoxide.nu

# A small native prompt: current directory plus a status-aware arrow. It does
# not launch an external prompt process.
$env.PROMPT_COMMAND = {||
    let directory = ($env.PWD | path basename)
    let arrow_color = if ($env.LAST_EXIT_CODE? | default 0) == 0 {
        ansi green_bold
    } else {
        ansi red_bold
    }

    $"(ansi cyan_bold)($directory)(ansi reset) ($arrow_color)❯(ansi reset) "
}
$env.PROMPT_COMMAND_RIGHT = {|| "" }
$env.PROMPT_INDICATOR = ""
$env.PROMPT_MULTILINE_INDICATOR = $"(ansi cyan)::: (ansi reset)"
